name: Release Build & CI

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    name: Test Matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.20.x, 1.21.x, 1.22.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Run tests
        run: go test ./...

  build:
    name: Build & Release Artifacts
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install dependencies
        run: sudo apt-get install -y fakeroot dpkg-dev rpm zip tar

      - name: Build binaries
        run: make build package checksums

      - name: Package .deb and .rpm
        run: make packages

      - name: Generate markdown changelog
        run: |
          echo "## $(date +%F) – v${GITHUB_REF_NAME#v}" >> CHANGELOG.md
          git log --pretty=format:"- %s (%an)" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> CHANGELOG.md

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*
